# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fe2a04964e5421040ca61344af1ddfc9c3fc5897b8db0b75edd8128427653f296c2191816bf8baf90f96620e784d1a6b6b7fb8033da8e3c1fbc92184754b21a

test:
  secret_key_base: 4d2e426c14dd8a9ab3fef746ead3dbabcf49ec39b3043df7a05978379a36ee3802850d3b7d54211c0d8a84fdb471cebabdd904543ae367b1e9912bd8ab2a60cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
